### ISSUE TITLE
模块不生效

### ISSUE THREAD

**Issue by Vstory** [LazyImmortal/Sesame#20]
### 程序版本 / 框架版本 / 模块版本

LSPosed 1.8.2(7058) 1.6.4

### 系统版本 / Android版本

13

### 详细描述问题发生的具体原因

什么都不改变，换成tk1.3.5可以正常运行。

清除tk版配置，删除目录
```
/storage/emulated/0/Android/media/com.eg.android.AlipayGphone/
```
后使用本项目1.6.4版本的芝麻粒，出现以下问题：
1.支付宝提示需要允许其读取芝麻粒权限
2.下方的报错信息

对于tk1.3.5和本项目的1.6.4均使用了hma，对支付宝隐藏。问题1出现后，取消隐藏后，冷启动支付宝，还是没有用。
不知道问题出在哪里，无法使用本项目的芝麻粒。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

```
12:32:43.429 ERROR: LibraryUtil, android.content.pm.PackageManager$NameNotFoundException: io.github.lazyimmortal.sesame
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:519)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:502)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:496)
	at io.github.lazyimmortal.sesame.util.LibraryUtil.getLibSesamePath(LibraryUtil.java:17)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook$3.afterHookedMethod(ApplicationHook.java:217)
	at WC.yhfBlM.MVMNreZoBScs.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.onCreate(Unknown Source:8)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4678)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:33)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:49)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
```
12:32:54.430 ERROR: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Notification$Builder android.app.Notification$Builder.setContentTitle(java.lang.CharSequence)' on a null object reference
	at io.github.lazyimmortal.sesame.util.NotificationUtil.sendText(NotificationUtil.java:137)
	at io.github.lazyimmortal.sesame.util.NotificationUtil.updateStatusText(NotificationUtil.java:106)
	at io.github.lazyimmortal.sesame.hook.ApplicationHook$4.afterHookedMethod(ApplicationHook.java:333)
	at WC.yhfBlM.MVMNreZoBScs.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:294)
	at LSPHooker_.onDestroy(Unknown Source:8)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4883)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub_private(SourceFile:33)
	at com.alipay.stability.workaround.a.a.__handleMessage_stub(Unknown Source:29)
	at com.alipay.dexaop.perf.CallbackHandleMessageChain.proceed1(SourceFile:15)
	at com.alipay.dexaop.monitor.chain.interceptors.RunningObjectInterceptor.intercept1(Unknown Source:89)
	at com.alipay.dexaop.perf.CallbackHandleMessageChain.proceed1(SourceFile:30)
	at com.alipay.dexaop.DexAOPEntrySettings.android_os_Handler_Callback_handleMessage_proxy(SourceFile:13)
	at com.alipay.dexaop.DexAOPEntry.android_os_Handler_Callback_handleMessage_proxy(Unknown Source:0)
	at com.alipay.stability.workaround.a.a.handleMessage(Unknown Source:44)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

</code></pre></details>

**Comment by LazyImmortal** [comment]
取消对支付宝隐藏芝麻粒

**Comment by Vstory** [comment]
> 取消对支付宝隐藏芝麻粒

取消了，然后冷启动支付宝，还是没反应的

**Comment by LazyImmortal** [comment]
> > 取消对支付宝隐藏芝麻粒
> 
> 取消了，然后冷启动支付宝，还是没反应的

试一下授予支付宝通知权限

**Comment by Vstory** [comment]
> 试一下授予支付宝通知权限


我上传的日志里有通知字段，我让gpt分析了下，检查了通知相关权限。
支付宝的通知都是允许的，通知分组里面也是允许的，但是日志报错，就是有这个字段。
我是真的搞不清楚问题出在哪里，实在没办法了。

![image](https://github.com/user-attachments/assets/f7796b8d-78c8-40e3-893b-8702cf76dfb4)

**Comment by Vstory** [comment]
通知类别（通知分组）里面，我都检查过来，全都允许通知了。
woy我也尝试了本项目的1.6.3版本，也是一样问题的。

但是换成TK1.3.5版本，就正常运行了。🤦‍♂️我也没做任何特殊操作，tk版使用hma对支付宝启动了隐藏，也能正常工作。

![image](https://github.com/user-attachments/assets/3727a542-3dba-4586-b781-cc75adfe5cb6)

**Comment by LazyImmortal** [comment]
1.6.4会有明确的失败提醒。如果没有报错我也不知道是什么问题。

**Comment by sheepeeing** [comment]
![17cab11b52958734f6e81baa90ffb0e](https://github.com/user-attachments/assets/f6fb1e63-eaae-4c3f-8616-beb2047a147c)
我这个是啥毛病

**Comment by LazyImmortal** [comment]
> ![17cab11b52958734f6e81baa90ffb0e](https://private-user-images.githubusercontent.com/179663323/395837584-f6fb1e63-eaae-4c3f-8616-beb2047a147c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDczMjcsIm5iZiI6MTczNDI0NzAyNywicGF0aCI6Ii8xNzk2NjMzMjMvMzk1ODM3NTg0LWY2ZmIxZTYzLWVhYWUtNGMzZi04NjE2LWJlYjIwNDdhMTQ3Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNzE3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjRmODMxNDE0MGNiZmE0NDVlM2IwYmQ3Yjk5MDlhODc1YjVmNWEzZDJlMTI4YTZjNDgwMzNjZDc1ODkzMDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-eWi_pt34qqkXdNULF6uKIpl2sNmq6eLVZxoDGwxZOM) 我这个是啥毛病

不支持内置模式！

**Comment by sheepeeing** [comment]
> > ![17cab11b52958734f6e81baa90ffb0e](https://private-user-images.githubusercontent.com/179663323/395837584-f6fb1e63-eaae-4c3f-8616-beb2047a147c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDczMjcsIm5iZiI6MTczNDI0NzAyNywicGF0aCI6Ii8xNzk2NjMzMjMvMzk1ODM3NTg0LWY2ZmIxZTYzLWVhYWUtNGMzZi04NjE2LWJlYjIwNDdhMTQ3Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNzE3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjRmODMxNDE0MGNiZmE0NDVlM2IwYmQ3Yjk5MDlhODc1YjVmNWEzZDJlMTI4YTZjNDgwMzNjZDc1ODkzMDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-eWi_pt34qqkXdNULF6uKIpl2sNmq6eLVZxoDGwxZOM) 我这个是啥毛病
> 
> 不支持内置模式！

大哥，这版本使用方式是什么？找不到哇

**Comment by Vstory** [comment]
> 1.6.4会有明确的失败提醒。如果没有报错我也不知道是什么问题。

收到

**Comment by sheepeeing** [comment]
> > 1.6.4会有明确的失败提醒。如果没有报错我也不知道是什么问题。
> 
> 收到

兄弟，怎么使用？是要和1.3.5同时运行吗

**Comment by sheepeeing** [comment]
> 我这个是啥毛病
> 
> 不支持内置模式！

我用了本地模式，好像可以用了。谢谢大哥
