### ISSUE TITLE
访问被拒绝 请检查是否使用了代理软件或vpn

### ISSUE THREAD

**Issue by dh53128** [LazyImmortal/Sesame#21]
### 程序版本 / 框架版本 / 模块版本

支付宝10.6.66.8000/Magisk 28000/LSPosed 1.92/芝麻粒 1.6.4.1

### 系统版本 / Android版本

Miui 12.5.1 Android 10

### 详细描述问题发生的具体原因

运行的时候会提示：访问被拒绝 请检查是否使用了代理软件或vpn
麻烦大佬帮忙看看是哪里设置错误了么

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(00:00:13.731 ERROR: new rpc response | id: 42615180 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
00:00:24.957 ERROR: new rpc response | id: 11965159 | method: alipay.antforest.forest.h5.grantEnergyRainChance args: [{"targetUserId":2088002004351595}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
00:00:36.530 ERROR: new rpc response | id: 29217514 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
00:01:49.553 ERROR: new rpc response | id: 37536091 | method: com.alipay.adexchange.ad.facade.xlightPlugin args: [{"positionRequest":{"extMap":{"xlightPlayInstanceId":"300004"},"referInfo":{},"spaceCode":"ANT_FARM_NEW_VILLAGE"},"sdkPageInfo":{"adComponentType":"FEEDS","adComponentVersion":"4.11.13","enableFusion":true,"networkType":"WIFI","pageFrom":"ch_url-https://68687809.h5app.alipay.com/www/game.html","pageNo":1,"pageUrl":"https://render.alipay.com/p/yuyan/180020010001256918/multi-stage-task.html?caprMode=sync&spaceCodeFeeds=ANT_FARM_NEW_VILLAGE&usePlayLink=true&xlightPlayInstanceId=300004","session":"u_54b721d9fffd6_1904b8eba8f","unionAppId":"2060090000309527","usePlayLink":"true","xlightSDKType":"h5","xlightSDKVersion":"4.11.13"}}] | data: {"adList":[],"ariverRpcTraceId":"2183011117342785073956461e3d6c","enableNewPlayingProto":true,"errorMsg":"this is a cheating traffic","extInfo":{},"pagingParam":{"hasNext":true,"pageNo":1,"pageSize":20,"session":"u_54b721d9fffd6_1904b8eba8f"},"playingResult":{"eventRewardDetail":{"browsingStepType":1,"eventHandleType":1,"eventRewardInfoList":[{"endOrder":0,"eventStep":15,"eventStepType":"duration","hasLoopEvent":false,"maxLoopCount":0,"noticeMediaFinish":false,"order":0,"playingEventType":"BROWSE","rewardId":40700005,"rewardNumber":3,"rewardRenderInfo":{"rewardDisplayAmount":"3","rewardDisplayText":"产速","rewardIcon":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*7_dJRY75kvoAAAAAAAAAAAAADsqsAQ/original","rewardUnitDisplayText":"/时"}},{"endOrder":0,"eventStep":15,"eventStepType":"duration","hasLoopEvent":false,"maxLoopCount":0,"noticeMediaFinish":false,"order":1,"playingEventType":"BROWSE","rewardId":40700005,"rewardNumber":3,"rewardRenderInfo":{"rewardDisplayAmount":"3","rewardDisplayText":"产速","rewardIcon":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*7_dJRY75kvoAAAAAAAAAAAAADsqsAQ/original","rewardUnitDisplayText":"/时"}}]},"playingBizId":"12b4c67246831a1f5128ee8f2413a4d7","playingBizStatus":0,"playingRenderSchema":{"floatPicture":{"defaultValue":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*c-ztRoAOZHsAAAAAAAAAAAAADsqsAQ/original"},"float_text":{"defaultValue":"滑动浏览15s得奖励","error":"网络异常","finished":"任务已完成"},"rewardArrows":{"defaultValue":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*0nBrTZ_WKs4AAAAAAAAAAAAADsqsAQ/original"},"rewardFrameTitle":{"defaultValue":"每浏览15秒可得1次奖励","sliding":""},"rewardFrameWordColor":{"defaultValue":"#6b421d"},"rewardPrefix":{"defaultValue":"+"},"topPicture":{"defaultValue":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*zOV0SL8Mr5gAAAAAAAAAAAAADsqsAQ/original","sliding":"https://mdn.alipayobjects.com/huamei_ouecfj/afts/img/A*GZ_RR4lCqaQAAAAAAAAAAAAADsqsAQ/original"},"topSubTitle":{"defaultValue":"滑动浏览或查看商品得奖励","sliding":""},"topTitle":{"defaultValue":"浏览得奖励","finished":"滑动浏览或查看商品"}},"playingStyleType":"BIZDOMAIN_COMMON_BROWSING_FEEDS","playingType":"BROWSING"},"retCode":"217","sspErrorCode":"61002","sspErrorMsg":"广告请求错误","xlightRequestId":"b7532098152243acbd741fee0b64be63"}
00:03:10.898 ERROR: new rpc response | id: 191382421 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412150090101600000000000088200919498138","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
00:03:11.002 ERROR: new rpc response | id: 25033005 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_FRAUD_LIABILITY","sendFlowNo":"202412160090101600000000000088200920331395","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":300000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"3000.00","userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
00:03:11.003 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

00:31:54.364 ERROR: new rpc response | id: 242868542 | method: alipay.antforest.forest.h5.startWhackMole args: [{"source":"chInfo_ch_appcenter__chsub_9patch"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
00:32:26.945 ERROR: new rpc response | id: 15859555 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
00:32:38.299 ERROR: new rpc response | id: 75917656 | method: alipay.antforest.forest.h5.grantEnergyRainChance args: [{"targetUserId":2088002004351595}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
00:32:49.706 ERROR: new rpc response | id: 41159246 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
00:33:06.726 ERROR: new rpc response | id: 73331336 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412150090101600000000000088200919498138","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
00:33:06.838 ERROR: new rpc response | id: 48400946 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412160090101600000000000088200920362029","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
00:33:06.944 ERROR: new rpc response | id: 214839928 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_FRAUD_LIABILITY","sendFlowNo":"202412160090101600000000000088200920331395","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":300000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"3000.00","userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
00:33:06.945 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

01:03:46.670 ERROR: new rpc response | id: 248179226 | method: alipay.antforest.forest.h5.startWhackMole args: [{"source":"chInfo_ch_appcenter__chsub_9patch"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:04:05.236 ERROR: new rpc response | id: 258251318 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
01:04:06.522 ERROR: new rpc response | id: 218930930 | method: alipay.antforest.forest.h5.grantEnergyRainChance args: [{"targetUserId":2088002004351595}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
01:04:07.819 ERROR: new rpc response | id: 256444266 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
01:04:20.819 ERROR: new rpc response | id: 77183211 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412150090101600000000000088200919498138","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:04:20.946 ERROR: new rpc response | id: 245223361 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412160090101600000000000088200920362029","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:04:21.086 ERROR: new rpc response | id: 226180479 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_FRAUD_LIABILITY","sendFlowNo":"202412160090101600000000000088200920331395","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":300000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"3000.00","userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:04:21.087 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

01:28:48.009 ERROR: java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at io.github.lazyimmortal.sesame.data.modelFieldExt.IntegerModelField.setConfigValue(IntegerModelField.java:55)
	at io.github.lazyimmortal.sesame.ui.NewSettingsActivity$WebViewCallback.setModel(NewSettingsActivity.java:310)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:181)
	at android.os.HandlerThread.run(HandlerThread.java:67)

01:34:50.416 ERROR: new rpc response | id: 258371844 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
01:35:04.002 ERROR: new rpc response | id: 263650143 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412150090101600000000000088200919498138","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:35:04.122 ERROR: new rpc response | id: 111407466 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412160090101600000000000088200920362029","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:35:04.261 ERROR: new rpc response | id: 218221346 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_FRAUD_LIABILITY","sendFlowNo":"202412160090101600000000000088200920331395","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":300000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"3000.00","userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:35:04.262 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

01:39:23.447 ERROR: new rpc response | id: 225820805 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
01:39:24.743 ERROR: new rpc response | id: 259903793 | method: alipay.antforest.forest.h5.startEnergyRain args: [{"version":"20240403"}] | data: {"error":1009,"errorMessage":"为了保障您的操作安全，请进行验证后继续。","errorNo":3,"errorTip":"1009"}
01:39:38.174 ERROR: new rpc response | id: 57416303 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412150090101600000000000088200919498138","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:39:38.277 ERROR: new rpc response | id: 134844011 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412160090101600000000000088200920362029","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:39:38.394 ERROR: new rpc response | id: 217585008 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_FRAUD_LIABILITY","sendFlowNo":"202412160090101600000000000088200920331395","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":300000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"3000.00","userId":"2088502183288827","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
01:39:38.395 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
)

</code></pre></details>

**Comment by xiaolanchong123** [comment]
楼上是不是 能量雨 和保险，关掉试试看
