### ISSUE TITLE
开启插件后支付宝需要滑块验证

### ISSUE THREAD

**Issue by kettly1260** [LazyImmortal/Sesame#8]
### 程序版本 / 框架版本 / 模块版本

支付宝10.5.90.8300/插件1.3.7/lsp 1.9.2

### 系统版本 / Android版本

安卓14

### 详细描述问题发生的具体原因

开启模块后支付宝弹出 未保障您的正常访问，请进行验证  的滑块，而且无法通过验证，关闭插件后提示消失

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
没日志……

**Comment by LazyImmortal** [comment]
才发现是1.3.7，上古版本了，更新下吧

**Comment by tpnet** [comment]
1.6.3，有保障金和运动两个问题 @LazyImmortal 
```
13:31:27.392 ERROR: new rpc response | id: 88521138 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219144820","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:31:27.512 ERROR: new rpc response | id: 194735943 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219383864","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:31:27.605 ERROR: new rpc response | id: 165783018 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219095765","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":3000000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"30000.00","userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:31:27.606 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

13:43:56.761 ERROR: AntSports, org.json.JSONException: No value for roomList
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONArray(JSONObject.java:593)
	at io.github.lazyimmortal.sesame.model.task.antSports.AntSports.queryClubHome(AntSports.java:1063)
	at io.github.lazyimmortal.sesame.model.task.antSports.AntSports.run(AntSports.java:153)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

13:43:59.828 ERROR: new rpc response | id: 96313600 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219144820","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:43:59.920 ERROR: new rpc response | id: 122527584 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219383864","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:44:00.010 ERROR: new rpc response | id: 223626342 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219095765","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":3000000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"30000.00","userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:44:00.011 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

13:59:02.948 ERROR: AntSports, org.json.JSONException: No value for roomList
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getJSONArray(JSONObject.java:593)
	at io.github.lazyimmortal.sesame.model.task.antSports.AntSports.queryClubHome(AntSports.java:1063)
	at io.github.lazyimmortal.sesame.model.task.antSports.AntSports.run(AntSports.java:153)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

13:59:05.987 ERROR: new rpc response | id: 265174037 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"ALIPAY_LOGIN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219144820","sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:59:06.089 ERROR: new rpc response | id: 59278986 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"YEB_SHOUYI_NEW","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219383864","sendSumInsured":{"cent":1800,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"18.00","sendType":1,"userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:59:06.189 ERROR: new rpc response | id: 57640035 | method: com.alipay.insgiftbff.insgiftMain.gainMyAndFamilySumInsured args: [{"channel":"DAILY_SIGN_IN","giftProdCode":"GIFT_UNIVERSAL_COVERAGE","realSendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"realSendSumInsuredYuan":"6.00","rightNo":"UNIVERSAL_SERIOUSNESS","sendFlowNo":"202412120090101600000000000031000219095765","sendFlowStatus":1,"sendSumInsured":{"cent":600,"currency":{"currencyCode":"CNY"}},"sendSumInsuredYuan":"6.00","sendType":1,"sumInsuredLimit":{"cent":3000000,"currency":{"currencyCode":"CNY"}},"sumInsuredLimitYuan":"30000.00","userId":"2088902958503100","entrance":"jkj_zhima_dairy66"}] | data: {"error":1009,"errorMessage":"系统繁忙，请稍后再试。","errorNo":3,"errorTip":"1009"}
13:59:06.190 ERROR: AntMember, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.github.lazyimmortal.sesame.data.modelFieldExt.BooleanModelField.getValue()' on a null object reference
	at io.github.lazyimmortal.sesame.model.task.antMember.AntMember.run(AntMember.java:108)
	at io.github.lazyimmortal.sesame.data.task.ModelTask$1.run(ModelTask.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
